@baseUrl = http://localhost:3000


# Messages
### List all messages
GET {{baseUrl}}/messages
# ?limit=30
# &offset=20

### Get one message by ID
GET {{baseUrl}}/messages/e4b6738f-ac80-460e-8d88-f6f42bc30313

### Create one message
POST {{baseUrl}}/messages
Content-Type: application/json

{
    "text": "Este é um recado NOVO para o Max! E é a 6ª msg.",
    "by": "Alefe",
    "to": "Max"
}

### Update one message by ID
PATCH {{baseUrl}}/messages/052fc188-5613-426d-8e86-5ff21bc428af
Content-Type: application/json

{
    "text": "Este é um recado NOVO para o Max!",
    "by": "Alefe",
    "to": "Max",
    "read": false
}

### Delete one message by ID
DELETE {{baseUrl}}/messages/2ca7e182-4c78-4bad-b5a4-cf05d63957ed


#


# Person
### List all persons
GET {{baseUrl}}/person
# ?limit=30
# &offset=20

### Get one person by ID
GET {{baseUrl}}/person/4ae13090-6a01-41c9-8833-ad0067c3a0ae

### Create one person
POST {{baseUrl}}/person
Content-Type: application/json

{
    "name": "Alefe Rocha Tavares",
    "email": "alefe@gmail.com",
    "password": "abc123"
}